##  Server Properties
server:
  port: 9090

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/devops?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093
    consumer:
      group-id: groupId
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  batch:
    job:
      names: loadProductsJob
      enabled: false
    jdbc:
      initialize-schema: ALWAYS

## Hibernate Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

## Kafka config
kafka:
  topic:
    name: stringTopic

## Spring Batch Config
batch:
  product:
    chunkValue: 5
    filePath: static/products.csv

## RSA Config
rsa:
  public-key: classpath:certs/pub.em
  rsa.private-key: classpath:certs/pri.pem

##
cdc:
  schema:
    history:
      internal:
        kafka:
          topic: schemaHistoryTopic
